name: Build and Push Docker Image (on tag)

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Adjust OS as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Ensure this is set to the correct context
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ env.TAG_NAME }}  # Replace with your image name

      - name: Build cache cleanup (optional)
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache  # Adjust path if needed
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-  # Wildcard to reuse cache across different tags

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Update values.yaml in other repos
        env:
          PAT: ${{ secrets.PAT }}
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          REPOS=("vdt-fe-helmChart")
          for repo in "${REPOS[@]}"; do
            git clone https://github:${{ secrets.PAT }}@github.com/theWorstSolution/$repo.git
            cd $repo
            sed -i 's/^appVersion: .*/appVersion: '${{ env.TAG_NAME }}'/' ./values.yaml
            git add .
            git commit -m "Update image version to ${{ env.TAG_NAME }}"
            git push https://github:${{ secrets.PAT }}@github.com/theWorstSolution/$repo.git
            cd ..
          done
